void setup()
{
  pinMode(13, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(11, OUTPUT);
  pinMode(10, OUTPUT);
  pinMode(9, OUTPUT);
  pinMode(8, OUTPUT);
}

void loop()
{
  digitalWrite(12, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(5000); 
  digitalWrite(12, LOW);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(800); 
  digitalWrite(12,HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(800); 
  digitalWrite(12, LOW);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(800); 
  digitalWrite(12,HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(800); 
  digitalWrite(12, LOW);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(800);
  digitalWrite(12, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(19, HIGH);
  delay(800); 
  digitalWrite(12, LOW);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  delay(800);
  
  digitalWrite(12, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(8, HIGH);
  delay(5000); 
  digitalWrite(12, LOW);
  digitalWrite(11, LOW);
  digitalWrite(9, HIGH);
  digitalWrite(8, HIGH);
  delay(800);
  digitalWrite(12, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(8, HIGH);
  delay(800); 
  digitalWrite(12, LOW);
  digitalWrite(11, LOW);
  digitalWrite(9, HIGH);
  digitalWrite(8, HIGH);
  delay(800);
  digitalWrite(12, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(8, HIGH);
  delay(800); 
  digitalWrite(12, LOW);
  digitalWrite(11, LOW);
  digitalWrite(9, HIGH);
  digitalWrite(8, HIGH);
  delay(800);
  digitalWrite(12, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(8, HIGH);
  delay(800); 
  digitalWrite(12, LOW);
  digitalWrite(11, LOW);
  digitalWrite(9, LOW);
  digitalWrite(8, LOW);
  delay(800);
  
  digitalWrite(10, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(5000); 
  digitalWrite(10, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800); 
  digitalWrite(10,HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800); 
  digitalWrite(10, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800); 
  digitalWrite(10,HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800); 
  digitalWrite(10, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800);
  digitalWrite(10, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800); 
  digitalWrite(10, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800);
  
  digitalWrite(10, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(5000); 
  digitalWrite(10, LOW);
  digitalWrite(9, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800);
  digitalWrite(10, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800); 
  digitalWrite(10, LOW);
  digitalWrite(9, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800);
  digitalWrite(10, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800); 
  digitalWrite(10, LOW);
  digitalWrite(9, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(800);
  digitalWrite(10, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(10, HIGH);
  delay(800); 
  digitalWrite(10, LOW);
  digitalWrite(9, LOW);
  digitalWrite(11, LOW);
  digitalWrite(10, LOW);
  delay(800);
  
}
